[package]
name = "geph4-exit"
version = "0.1.1-alpha.0"
authors = ["nullchinchilla <nullchinchilla@pm.me>", "Geph Project <contact@geph.io"]
edition = "2018"
description="Exit node for Geph"
license="GPL-3.0-only"
repository="https://github.com/geph-official/geph4-exit"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# binder_transport = {path="../lib/binder_transport"}
smol= "1.2.5"
env_logger = "0.9.0"
log= "0.4.14"
structopt= "0.3.22"
ed25519-dalek={ version = "1.0.1", features = ["serde"] }
rand= "0.7.3"
bincode= "1.3.3"
anyhow= "1.0.42"
hex= "0.4.3"
x25519-dalek={ version = "1.1.1", features = ["serde"] }
sosistab= "0.4.11"
# sosistab={ path="../sosistab"}
blake3= "1.0.0"
serde= "1.0.127"
# mizaru={path="../lib/mizaru"} 
once_cell= "1.8.0"
smolscale = "0.3.12"
smol-timeout = "0.6.0"
statsd = "0.14.1"
num_cpus= "1.13.0"
scopeguard= "1.1.0"
parking_lot= "0.11.1"
# tundevice={path="../lib/tundevice"}
jemalloc-ctl= "0.3.3"
cidr= "0.1.1"
bytes= "1.0.1"
lru= "0.6.6"
pnet_packet= "0.28.0"
rangemap= "0.1.11"
dashmap= "4.0.2"
governor= "0.3.2"
# aioutils={path="../lib/aioutils"}
# vpn_structs={path="../lib/vpn_structs"}

libc= "0.2.99"
os_socketaddr= "0.2.0"
ureq= "1.5.5"
flate2= "1.0.20"
async-dup= "1.2.2"
fastrand= "1.5.0"

cached= "0.24.1"
rustc-hash= "1.1.0"
jemallocator= "0.3.2"

futures-util= "0.3.16"
geph4-binder-transport = "0.1.3"
geph4-aioutils = "0.1.2"
geph4-protocol = "0.1.0"
mizaru = "0.1.3"
tundevice = "0.1.3"

# reed-solomon-erasure = { version = "4.0.2", features = [ "simd-accel" ] }
getset = "0.1.1"

toml= "0.5.8"
serde_json = "1.0.66"

[profile.release]
panic = "abort"
opt-level=3
debug=2

# [patch.crates-io]
# sosistab={path="../sosistab"}
