version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.53.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Install musl toolchain
          command: "rustup target add x86_64-unknown-linux-musl"
      - run:
          name: Install cross
          command: "cargo install cross"
      - run:
          name: Build for musl
          command: "cross build --locked --release --target x86_64-unknown-linux-musl"
