version: 2.1

jobs:
  build:
    working_directory: ~/repo/
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: cargo install cross
      - run: cross build --locked --release --target x86_64-unknown-linux-musl
