version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.53.0
    steps:
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - checkout
      - run: cargo --version
      - run:
          name: Install cross
          command: "cargo install cross"
      - run:
          name: Build for musl
          command: "cross build --locked --release --target x86_64-unknown-linux-gnu"
